services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: amizhthan
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin4:
    image: elestio/pgadmin:latest
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: amizhthan.md@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8888:8080"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
  pgadmin_data:
